// Export Service for Downloading Data as JSON, PDF, etc.

import { storageService, Quiz, StudyPlan, Note } from './storageService'

class ExportService {
  // Download JSON file
  private downloadJSON(data: any, filename: string): void {
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' })
    this.downloadBlob(blob, filename)
  }

  // Download text file
  private downloadText(content: string, filename: string): void {
    const blob = new Blob([content], { type: 'text/plain' })
    this.downloadBlob(blob, filename)
  }

  // Generic blob download
  private downloadBlob(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = filename
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  // Format date for filenames
  private formatDateForFilename(): string {
    const now = new Date()
    return now.toISOString().split('T')[0] // YYYY-MM-DD
  }

  // Export single quiz as JSON
  exportQuizJSON(quiz: Quiz): void {
    const filename = `quiz_${quiz.topic.replace(/\s+/g, '_')}_${this.formatDateForFilename()}.json`
    this.downloadJSON(quiz, filename)
  }

  // Export quiz result as JSON
  exportQuizResultJSON(quiz: Quiz): void {
    if (!quiz.result) {
      alert('No quiz result to export')
      return
    }

    const resultData = {
      quiz: {
        id: quiz.id,
        topic: quiz.topic,
        difficulty: quiz.difficulty,
        totalQuestions: quiz.questions.length
      },
      result: quiz.result,
      exportedAt: new Date().toISOString()
    }

    const filename = `quiz_result_${quiz.topic.replace(/\s+/g, '_')}_${this.formatDateForFilename()}.json`
    this.downloadJSON(resultData, filename)
  }

  // Export quiz result as text report
  exportQuizResultText(quiz: Quiz): void {
    if (!quiz.result) {
      alert('No quiz result to export')
      return
    }

    const result = quiz.result
    let report = `
╔════════════════════════════════════════════════════════════╗
║              ACEMIND QUIZ RESULT REPORT                    ║
╚════════════════════════════════════════════════════════════╝

Quiz Topic: ${quiz.topic}
Difficulty: ${quiz.difficulty}
Date: ${new Date(result.completedAt).toLocaleString()}

═══════════════════════════════════════════════════════════════

SCORE SUMMARY
─────────────────────────────────────────────────────────────
Score:          ${result.score} / ${result.totalQuestions}
Percentage:     ${result.percentage}%
Time Spent:     ${Math.floor(result.timeSpent / 60)}m ${result.timeSpent % 60}s
Performance:    ${this.getPerformanceLabel(result.percentage)}

═══════════════════════════════════════════════════════════════

DETAILED RESULTS
─────────────────────────────────────────────────────────────
`

    result.detailedResults.forEach((item, index) => {
      const status = item.isCorrect ? '✓ CORRECT' : '✗ INCORRECT'
      report += `
Question ${index + 1}: ${status}
${item.question}

Your Answer:    ${item.userAnswer || '(No answer)'}
Correct Answer: ${item.correctAnswer}
${item.explanation ? `\nExplanation: ${item.explanation}` : ''}

─────────────────────────────────────────────────────────────
`
    })

    report += `
═══════════════════════════════════════════════════════════════

Generated by AceMind - AI-Powered Study Platform
Export Date: ${new Date().toLocaleString()}
`

    const filename = `quiz_result_${quiz.topic.replace(/\s+/g, '_')}_${this.formatDateForFilename()}.txt`
    this.downloadText(report, filename)
  }

  private getPerformanceLabel(percentage: number): string {
    if (percentage >= 90) return 'Excellent! 🏆'
    if (percentage >= 80) return 'Great! 🎉'
    if (percentage >= 70) return 'Good! 👏'
    if (percentage >= 60) return 'Fair 👍'
    return 'Needs Improvement 💪'
  }

  // Export study plan as JSON
  exportStudyPlanJSON(plan: StudyPlan): void {
    const filename = `study_plan_${this.formatDateForFilename()}.json`
    this.downloadJSON(plan, filename)
  }

  // Export study plan as text
  exportStudyPlanText(plan: StudyPlan): void {
    let report = `
╔════════════════════════════════════════════════════════════╗
║              ACEMIND STUDY PLAN                            ║
╚════════════════════════════════════════════════════════════╝

Exam Date: ${new Date(plan.examDate).toLocaleDateString()}
Daily Study Hours: ${plan.dailyStudyHours}
Created: ${new Date(plan.createdAt).toLocaleDateString()}

Goals:
${plan.goals || 'No specific goals set'}

═══════════════════════════════════════════════════════════════

SUBJECTS
─────────────────────────────────────────────────────────────
`

    plan.subjects.forEach((subject, index) => {
      report += `
${index + 1}. ${subject.name} - ${subject.topic}
   Difficulty: ${subject.difficulty}
   Priority: ${subject.priority}
`
    })

    report += `
═══════════════════════════════════════════════════════════════

DAILY SCHEDULE
─────────────────────────────────────────────────────────────
`

    plan.dailyPlans.forEach((day, index) => {
      const date = new Date(day.date)
      const dayName = date.toLocaleDateString('en-US', { weekday: 'long', month: 'short', day: 'numeric' })
      
      report += `
Day ${index + 1}: ${dayName}
Total Hours: ${day.totalHours}h
Tasks: ${day.tasks.length}

`
      day.tasks.forEach((task: any, taskIndex: number) => {
        const status = task.completed ? '[✓]' : '[ ]'
        report += `  ${status} ${taskIndex + 1}. ${task.title} (${task.estimatedDuration}min)\n`
      })
      
      report += `─────────────────────────────────────────────────────────────\n`
    })

    report += `
═══════════════════════════════════════════════════════════════

PROGRESS
─────────────────────────────────────────────────────────────
Completed Tasks: ${plan.progress.completedTasks} / ${plan.progress.totalTasks}
Progress: ${plan.progress.percentage}%

═══════════════════════════════════════════════════════════════

Generated by AceMind - AI-Powered Study Platform
Export Date: ${new Date().toLocaleString()}
`

    const filename = `study_plan_${this.formatDateForFilename()}.txt`
    this.downloadText(report, filename)
  }

  // Export study plan as iCal for calendar import
  exportStudyPlanICal(plan: StudyPlan): void {
    let ical = `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//AceMind//Study Plan//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:AceMind Study Plan
X-WR-TIMEZONE:UTC
X-WR-CALDESC:Study plan generated by AceMind

`

    plan.dailyPlans.forEach((day) => {
      day.tasks.forEach((task: any) => {
        const date = new Date(day.date)
        const startDate = date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z'
        
        // Add task duration to get end time
        const endDate = new Date(date.getTime() + task.estimatedDuration * 60000)
        const endDateStr = endDate.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z'

        ical += `BEGIN:VEVENT
UID:${task.id}@acemind.app
DTSTAMP:${new Date().toISOString().replace(/[-:]/g, '').split('.')[0]}Z
DTSTART:${startDate}
DTEND:${endDateStr}
SUMMARY:${task.title}
DESCRIPTION:${task.description || ''}
CATEGORIES:Study,${task.subject}
STATUS:${task.completed ? 'COMPLETED' : 'CONFIRMED'}
END:VEVENT

`
      })
    })

    ical += 'END:VCALENDAR'

    const blob = new Blob([ical], { type: 'text/calendar' })
    const filename = `study_plan_${this.formatDateForFilename()}.ics`
    this.downloadBlob(blob, filename)
  }

  // Export note as Markdown
  exportNoteMarkdown(note: Note): void {
    let markdown = `# ${note.title}\n\n`
    
    if (note.tags.length > 0) {
      markdown += `**Tags:** ${note.tags.map(tag => `#${tag}`).join(', ')}\n\n`
    }
    
    markdown += `**Created:** ${new Date(note.createdAt).toLocaleString()}\n`
    markdown += `**Updated:** ${new Date(note.updatedAt).toLocaleString()}\n\n`
    markdown += `---\n\n`
    markdown += note.content
    markdown += `\n\n---\n\n`
    markdown += `*Generated by AceMind*`

    const filename = `note_${note.title.replace(/\s+/g, '_')}_${this.formatDateForFilename()}.md`
    this.downloadText(markdown, filename)
  }

  // Export all notes as Markdown files in a ZIP (requires JSZip)
  async exportAllNotesMarkdown(): Promise<void> {
    const notes = storageService.getNotes()
    
    if (notes.length === 0) {
      alert('No notes to export')
      return
    }

    // For now, export as a single combined file
    // TODO: Add JSZip for multiple files
    let combined = `# AceMind Notes Export\n\n`
    combined += `Exported: ${new Date().toLocaleString()}\n`
    combined += `Total Notes: ${notes.length}\n\n`
    combined += `═══════════════════════════════════════════════════════════════\n\n`

    notes.forEach((note, index) => {
      combined += `## ${index + 1}. ${note.title}\n\n`
      if (note.tags.length > 0) {
        combined += `**Tags:** ${note.tags.map(tag => `#${tag}`).join(', ')}\n\n`
      }
      combined += `**Created:** ${new Date(note.createdAt).toLocaleString()}\n\n`
      combined += note.content
      combined += `\n\n═══════════════════════════════════════════════════════════════\n\n`
    })

    const filename = `all_notes_${this.formatDateForFilename()}.md`
    this.downloadText(combined, filename)
  }

  // Export analytics report
  exportAnalyticsReport(): void {
    const analytics = storageService.getAnalytics()
    const quizzes = storageService.getQuizzes()
    const plans = storageService.getStudyPlans()

    let report = `
╔════════════════════════════════════════════════════════════╗
║              ACEMIND ANALYTICS REPORT                      ║
╚════════════════════════════════════════════════════════════╝

Report Generated: ${new Date().toLocaleString()}
Last Activity: ${new Date(analytics.lastActivity).toLocaleString()}

═══════════════════════════════════════════════════════════════

OVERALL STATISTICS
─────────────────────────────────────────────────────────────
Total Quizzes Completed:  ${analytics.totalQuizzes}
Average Score:            ${analytics.averageScore}%
Total Study Time:         ${analytics.totalStudyTime} hours
Total Notes:              ${analytics.totalNotes}
Study Streak:             ${analytics.studyStreak} days

═══════════════════════════════════════════════════════════════

QUIZ PERFORMANCE
─────────────────────────────────────────────────────────────
`

    const completedQuizzes = quizzes.filter(q => q.result)
    completedQuizzes.forEach((quiz, index) => {
      if (quiz.result) {
        report += `
${index + 1}. ${quiz.topic}
   Score: ${quiz.result.score}/${quiz.result.totalQuestions} (${quiz.result.percentage}%)
   Time: ${Math.floor(quiz.result.timeSpent / 60)}m ${quiz.result.timeSpent % 60}s
   Date: ${new Date(quiz.result.completedAt).toLocaleDateString()}
`
      }
    })

    report += `
═══════════════════════════════════════════════════════════════

STUDY PLANS
─────────────────────────────────────────────────────────────
Total Plans: ${plans.length}

`

    plans.forEach((plan, index) => {
      report += `
${index + 1}. Plan for ${new Date(plan.examDate).toLocaleDateString()}
   Subjects: ${plan.subjects.length}
   Total Tasks: ${plan.progress.totalTasks}
   Completed: ${plan.progress.completedTasks} (${plan.progress.percentage}%)
   Daily Hours: ${plan.dailyStudyHours}h
`
    })

    report += `
═══════════════════════════════════════════════════════════════

STORAGE INFORMATION
─────────────────────────────────────────────────────────────
`

    const storageInfo = storageService.getStorageInfo()
    report += `
Used Storage: ${storageInfo.usedMB} MB / ${storageInfo.maxMB} MB (${storageInfo.percentageUsed}%)
Quizzes: ${storageInfo.itemCounts.quizzes}
Study Plans: ${storageInfo.itemCounts.studyPlans}
Notes: ${storageInfo.itemCounts.notes}

═══════════════════════════════════════════════════════════════

Generated by AceMind - AI-Powered Study Platform
`

    const filename = `analytics_report_${this.formatDateForFilename()}.txt`
    this.downloadText(report, filename)
  }

  // Export all data as JSON
  exportAllDataJSON(): void {
    const allData = storageService.exportAllData()
    const filename = `acemind_backup_${this.formatDateForFilename()}.json`
    this.downloadJSON(allData, filename)
  }

  // Import data from JSON file
  async importDataFromFile(file: File): Promise<{ success: boolean; message: string }> {
    try {
      const text = await file.text()
      const data = JSON.parse(text)
      return storageService.importData(data)
    } catch (error) {
      console.error('Import error:', error)
      return { success: false, message: 'Invalid file format' }
    }
  }
}

export const exportService = new ExportService()
