import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface QuizResult {
  score: number;
  totalQuestions: number;
  percentage: number;
  timeSpent: number;
  detailedResults: {
    questionId: string;
    question: string;
    userAnswer: string;
    correctAnswer: string;
    isCorrect: boolean;
    explanation?: string;
  }[];
}

interface QuizData {
  topic: string;
  difficulty: string;
}

export const generateQuizReportPDF = (
  quizResults: QuizResult,
  quizData: QuizData
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header with gradient effect (simulated with colors)
  doc.setFillColor(79, 70, 229); // Indigo
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Quiz Report', pageWidth / 2, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Topic: ${quizData.topic}`, pageWidth / 2, 30, { align: 'center' });
  
  // Reset text color
  doc.setTextColor(0, 0, 0);
  
  // Date and Time
  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 50);
  
  // Score Summary Box
  doc.setFillColor(240, 240, 255);
  doc.roundedRect(14, 60, pageWidth - 28, 40, 3, 3, 'F');
  
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Score Summary', 20, 72);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Score: ${quizResults.score}/${quizResults.totalQuestions}`, 20, 82);
  doc.text(`Percentage: ${quizResults.percentage}%`, 20, 90);
  doc.text(`Time Taken: ${formatTime(quizResults.timeSpent)}`, 100, 82);
  doc.text(`Avg per Question: ${Math.round(quizResults.timeSpent / quizResults.totalQuestions)}s`, 100, 90);
  
  // Performance indicator
  const performance = getPerformanceText(quizResults.percentage);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(performance.color[0], performance.color[1], performance.color[2]);
  doc.text(`Performance: ${performance.text}`, 20, 98);
  doc.setTextColor(0, 0, 0);
  
  // Detailed Results
  let yPos = 115;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Detailed Results', 14, yPos);
  
  yPos += 10;
  
  // Create table data
  const tableData = quizResults.detailedResults.map((result, index) => [
    `Q${index + 1}`,
    result.question.substring(0, 60) + (result.question.length > 60 ? '...' : ''),
    result.userAnswer.substring(0, 30),
    result.correctAnswer.substring(0, 30),
    result.isCorrect ? '✓' : '✗'
  ]);
  
  autoTable(doc, {
    startY: yPos,
    head: [['#', 'Question', 'Your Answer', 'Correct Answer', 'Result']],
    body: tableData,
    theme: 'striped',
    headStyles: {
      fillColor: [79, 70, 229],
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    },
    columnStyles: {
      0: { cellWidth: 15 },
      1: { cellWidth: 70 },
      2: { cellWidth: 40 },
      3: { cellWidth: 40 },
      4: { cellWidth: 20, halign: 'center' }
    },
    didParseCell: (data) => {
      if (data.column.index === 4 && data.section === 'body') {
        const isCorrect = data.cell.text[0] === '✓';
        data.cell.styles.textColor = isCorrect ? [34, 197, 94] : [239, 68, 68];
        data.cell.styles.fontStyle = 'bold';
      }
    }
  });
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${pageCount} | Generated by AceMind`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }
  
  // Save the PDF
  doc.save(`quiz-report-${quizData.topic.replace(/\s+/g, '-')}-${Date.now()}.pdf`);
};

export const generateStudyPlanPDF = (
  dayPlans: any[],
  studyPlanInput: any,
  daysUntilExam: number,
  tasks: any[]
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header
  doc.setFillColor(99, 102, 241); // Indigo
  doc.rect(0, 0, pageWidth, 45, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(26);
  doc.setFont('helvetica', 'bold');
  doc.text('AI Study Plan', pageWidth / 2, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`${daysUntilExam} days until exam`, pageWidth / 2, 32, { align: 'center' });
  
  doc.setTextColor(0, 0, 0);
  
  // Plan Details
  let yPos = 55;
  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, yPos);
  doc.text(`Exam Date: ${studyPlanInput.examDate}`, 14, yPos + 6);
  doc.text(`Daily Study Hours: ${studyPlanInput.dailyStudyHours}h`, 14, yPos + 12);
  
  // Goals Box
  yPos += 25;
  doc.setFillColor(240, 253, 244);
  doc.roundedRect(14, yPos, pageWidth - 28, 25, 3, 3, 'F');
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Study Goals', 20, yPos + 8);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const goals = studyPlanInput.goals || 'No specific goals set';
  const splitGoals = doc.splitTextToSize(goals, pageWidth - 40);
  doc.text(splitGoals, 20, yPos + 16);
  
  // Subjects Summary
  yPos += 35;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Subjects', 14, yPos);
  
  yPos += 8;
  const subjectsData = studyPlanInput.subjects.map((s: any, i: number) => [
    `${i + 1}`,
    s.name,
    s.topic,
    s.difficulty,
    s.priority
  ]);
  
  autoTable(doc, {
    startY: yPos,
    head: [['#', 'Subject', 'Topic', 'Difficulty', 'Priority']],
    body: subjectsData,
    theme: 'grid',
    headStyles: {
      fillColor: [99, 102, 241],
      textColor: [255, 255, 255],
      fontStyle: 'bold'
    },
    columnStyles: {
      0: { cellWidth: 15 },
      1: { cellWidth: 40 },
      2: { cellWidth: 50 },
      3: { cellWidth: 35 },
      4: { cellWidth: 35 }
    }
  });
  
  // Day-wise Plan
  doc.addPage();
  yPos = 20;
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Day-wise Study Schedule', 14, yPos);
  
  yPos += 10;
  
  dayPlans.forEach((dayPlan, index) => {
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }
    
    // Day header
    doc.setFillColor(243, 244, 246);
    doc.roundedRect(14, yPos, pageWidth - 28, 12, 2, 2, 'F');
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(
      `Day ${index + 1} - ${new Date(dayPlan.date).toLocaleDateString()}`,
      20,
      yPos + 8
    );
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text(
      `${dayPlan.totalHours.toFixed(1)}h | ${dayPlan.completed}/${dayPlan.tasks.length} completed`,
      pageWidth - 20,
      yPos + 8,
      { align: 'right' }
    );
    
    yPos += 18;
    
    // Tasks table
    const tasksData = dayPlan.tasks.map((task: any, i: number) => [
      `${i + 1}`,
      task.subject,
      task.topic,
      `${task.duration}m`,
      task.completed ? '✓' : '○'
    ]);
    
    autoTable(doc, {
      startY: yPos,
      head: [['#', 'Subject', 'Topic', 'Duration', 'Status']],
      body: tasksData,
      theme: 'plain',
      headStyles: {
        fillColor: [229, 231, 235],
        textColor: [0, 0, 0],
        fontStyle: 'bold',
        fontSize: 9
      },
      bodyStyles: {
        fontSize: 9
      },
      columnStyles: {
        0: { cellWidth: 15 },
        1: { cellWidth: 45 },
        2: { cellWidth: 70 },
        3: { cellWidth: 25 },
        4: { cellWidth: 20, halign: 'center' }
      },
      didParseCell: (data) => {
        if (data.column.index === 4 && data.section === 'body') {
          const isCompleted = data.cell.text[0] === '✓';
          data.cell.styles.textColor = isCompleted ? [34, 197, 94] : [156, 163, 175];
        }
      }
    });
    
    yPos = (doc as any).lastAutoTable.finalY + 15;
  });
  
  // Summary Page
  doc.addPage();
  yPos = 20;
  
  doc.setFillColor(79, 70, 229);
  doc.rect(0, 0, pageWidth, 50, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Study Plan Summary', pageWidth / 2, 30, { align: 'center' });
  
  doc.setTextColor(0, 0, 0);
  yPos = 70;
  
  const completedTasks = tasks.filter(t => t.completed).length;
  const totalHours = dayPlans.reduce((sum, day) => sum + day.totalHours, 0);
  const progress = tasks.length > 0 ? Math.round((completedTasks / tasks.length) * 100) : 0;
  
  // Summary boxes
  const summaryData = [
    ['Total Tasks', tasks.length.toString()],
    ['Completed Tasks', completedTasks.toString()],
    ['Remaining Tasks', (tasks.length - completedTasks).toString()],
    ['Total Study Hours', `${totalHours.toFixed(1)}h`],
    ['Overall Progress', `${progress}%`],
    ['Days Until Exam', daysUntilExam.toString()]
  ];
  
  autoTable(doc, {
    startY: yPos,
    body: summaryData,
    theme: 'grid',
    columnStyles: {
      0: { cellWidth: 90, fontStyle: 'bold', fillColor: [243, 244, 246] },
      1: { cellWidth: 90, halign: 'center', fontSize: 14, fontStyle: 'bold' }
    }
  });
  
  // Motivational message
  yPos = (doc as any).lastAutoTable.finalY + 20;
  doc.setFillColor(254, 249, 195);
  doc.roundedRect(14, yPos, pageWidth - 28, 30, 3, 3, 'F');
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('💪 Stay Focused!', pageWidth / 2, yPos + 12, { align: 'center' });
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(
    'Consistency is key. Follow your plan and you\'ll achieve your goals!',
    pageWidth / 2,
    yPos + 22,
    { align: 'center' }
  );
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${pageCount} | Generated by AceMind | ${new Date().toLocaleDateString()}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }
  
  doc.save(`study-plan-${new Date().toISOString().split('T')[0]}.pdf`);
};

// Helper functions
const formatTime = (seconds: number): string => {
  const mins = Math.floor(seconds / 60);
  const secs = seconds % 60;
  return `${mins}:${secs.toString().padStart(2, '0')}`;
};

const getPerformanceText = (percentage: number): { text: string; color: number[] } => {
  if (percentage >= 90) return { text: 'Excellent! 🏆', color: [34, 197, 94] };
  if (percentage >= 80) return { text: 'Very Good! 🌟', color: [59, 130, 246] };
  if (percentage >= 70) return { text: 'Good! 👍', color: [168, 85, 247] };
  if (percentage >= 60) return { text: 'Fair 📚', color: [251, 146, 60] };
  return { text: 'Needs Improvement 💪', color: [239, 68, 68] };
};
